name: CI/CD Pushup Detector

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install uvicorn gunicorn # Для запуска в CI/CD и Heroku

    - name: Prepare Data (Use relative paths)
      run: |
        mkdir -p data
        cp angles.csv data/
        cp labels.csv data/

    - name: Train Model
      run: python train_model.py

    - name: Run Tests
      run: pytest test_api.py

  deploy_api:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy FastAPI API to Heroku
      uses: dineshsonachalam/heroku-deploy@v2.0.2
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_API_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        workingdir: .